### ISSUE TITLE
not enough balls

### ISSUE THREAD

**Issue by skoove** [skoove/BallSimulator#2]

**Comment by cinder-OwO** [comment]
make more
it's veryhot

**Comment by skoove** [comment]
pleasess fix

**Comment by cinder-OwO** [comment]
it is fix
prees  " "

**Comment by skoove** [comment]
no

**Comment by cinder-OwO** [comment]
KILLL YOURSELF YOU FUCKING PIECE OF SHIT YOU AND YOUR ENTIRE FAMILY CA BURN IN A HOUSE FIRE BECAUSE YOU SUCK SHIG AT SPAWNENDSING BALLS :RAGE:

**Comment by skoove** [comment]
thats not very nice

**Comment by cinder-OwO** [comment]
:3

**Comment by skoove** [comment]
wow thas reallly cute :3

**Comment by cinder-OwO** [comment]
:3 praise me more~

**Comment by skoove** [comment]
your so god :paperclip:

**Comment by cinder-OwO** [comment]
NO WAY IS THAT CLEEPY HIMSELF

**Comment by cinder-OwO** [comment]
CLIPPERS

**Comment by cinder-OwO** [comment]
CLIPPITY CLOP

**Comment by skoove** [comment]
oh yeah clippity clop me harder :3 ~

**Comment by cinder-OwO** [comment]
~~~~~

**Comment by cinder-OwO** [comment]
~

**Comment by cinder-OwO** [comment]
~

**Comment by cinder-OwO** [comment]
~

**Comment by cinder-OwO** [comment]
~

**Comment by skoove** [comment]
wow your really ~ rn

**Comment by cinder-OwO** [comment]
i have to use a slutty amnount of ~s in sepparate mesages

**Comment by cinder-OwO** [comment]
3:

**Comment by skoove** [comment]
ew what the fuuck im breaking up withyou

**Comment by cinder-OwO** [comment]
NOOOOOOOOOO

**Comment by skoove** [comment]
goodbye.

**Comment by cinder-OwO** [comment]
[rensenware-cut-master.zip](https://github.com/skoove/BallSimulator/files/12330822/rensenware-cut-master.zip)
I'M SORRY HERE IS THE FIX YOU ASKED FOR

**Comment by cinder-OwO** [comment]
I'LL EVEN :3 FOR OUPLS PSLSPLS

**Comment by cinder-OwO** [comment]
NOOOOOOOOOOO
